// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sozshospyrfnmwmtazws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvenNob3NweXJmbm13bXRhendzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMzE5ODMsImV4cCI6MjA2NTgwNzk4M30.dE2xvcAL4WAMhlvh4Egg_4uH7qGt5zt3l8LE7d8xYoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);